### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by andrewpedia** [astonbitecode/j4rs#100]
Exception in thread "main" java.lang.VerifyError: Expecting a stackmap frame at branch target 57
Exception Details:
  Location:
   : if_icmpge
  Reason:
    Expected stackmap frame at this location.

**Comment by andrewpedia** [comment]
how to disable verify

**Comment by astonbitecode** [comment]
Can you please provide more details (plus logs if possible) of what you try to achieve and what are the results?

**Comment by andrewpedia** [comment]
Exception in thread "main" java.lang.VerifyError: Expecting a stackmap frame at branch target 106
Exception Details:
  Location:
    com/aa/bb/cc.<clinit>()V @97: ifne
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: 0313 0012 0413 0012 0323 0020 0411 0011
    ..............
     
  Exception Handler Table:
    bci [116, 119] => handler: 120

	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.astonbitecode.j4rs.utils.Utils.forNameEnhanced(Utils.java:56)
	at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.createForStatic(NativeInstantiationImpl.java:53)
ERROR: An Exception was thrown by Java... Please check the logs or the console.
Exception in thread "main" java.lang.NullPointerException
Error: JavaError("An Exception was thrown by Java... Please check the logs or the console.")
