### ISSUE TITLE
Unable to get field after adding an object into arraylist and retrieving it

### ISSUE THREAD

**Issue by showier-drastic** [astonbitecode/j4rs#134]
You can see in the code below: the `good()` just retrieves a field from a newly-created object without problems; but in the `bad()` example, after I insert the object into an ArrayList and then retrieve it with `get()`, its fields become inaccessible. Method calls (at least `toString()`) works fine though.

Environment: macOS + OpenJDK23

Step to reproduce:

1. Create an empty rust project
2. `cargo add j4rs`
3. Download https://repo1.maven.org/maven2/com/itextpdf/itextpdf/5.5.13.4/itextpdf-5.5.13.4.jar into the working directory
4. Add main.rs, and run:

```rust
use j4rs::{errors::J4RsError, ClasspathEntry, Instance, InvocationArg, Jvm, JvmBuilder};

fn try_get_field_from_pos(jvm: &Jvm, pos: Instance) -> Result<(), J4RsError> {
    println!("class_name of pos0: {:?}", pos.class_name());

    let pos0_str = jvm.invoke(&pos, "toString", InvocationArg::empty())?;
    println!("pos0 to string: {:?}", jvm.to_rust::<String>(pos0_str)?);

    let position = jvm.field(&pos, "position")?;
    let page = jvm.field(&pos, "page")?;

    println!("page: {}", jvm.to_rust::<i32>(page)?);

    Ok(())
}

fn create_pos0(jvm: &Jvm) -> Result<Instance, J4RsError> {
    let pos0 = jvm.create_instance(
        "com.itextpdf.text.pdf.AcroFields$FieldPosition",
        InvocationArg::empty(),
    )?;

    Ok(pos0)
}

fn good() -> Result<(), J4RsError> {
    let entry = ClasspathEntry::new("./itextpdf-5.5.13.4.jar");
    let jvm = JvmBuilder::new().classpath_entry(entry).build()?;

    let pos0 = create_pos0(&jvm)?;

    try_get_field_from_pos(&jvm, pos0)?;

    Ok(())
}

fn bad() -> Result<(), J4RsError> {
    let entry = ClasspathEntry::new("./itextpdf-5.5.13.4.jar");
    let jvm = JvmBuilder::new().classpath_entry(entry).build()?;

    let pos = create_pos0(&jvm)?;

    let list = jvm.create_instance("java.util.ArrayList", InvocationArg::empty())?;
    jvm.invoke(&list, "add", &[InvocationArg::from(pos)])?;

    let pos0 = jvm.invoke(
        &list,
        "get",
        &[InvocationArg::try_from(0i32)?.into_primitive()?],
    )?;

    try_get_field_from_pos(&jvm, pos0)?;

    Ok(())
}

fn main() {
    println!("====== good ======");
    good().unwrap();
    println!("====== bad ======");
    bad().unwrap();
}
```

Output:

```
====== good ======
class_name of pos0: "com.itextpdf.text.pdf.AcroFields$FieldPosition"
pos0 to string: "com.itextpdf.text.pdf.AcroFields$FieldPosition@735b5592"
page: 0
====== bad ======
class_name of pos0: "known_in_java_world"
pos0 to string: "com.itextpdf.text.pdf.AcroFields$FieldPosition@52b05295"
Exception in thread "Thread-0" org.astonbitecode.j4rs.errors.InvocationException: Error while accessing field position of Class java.lang.Object
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.field(JsonInvocationImpl.java:141)
Caused by: java.lang.NoSuchFieldException: position
        at java.base/java.lang.Class.getField(Class.java:2343)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.getField(JsonInvocationImpl.java:167)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.field(JsonInvocationImpl.java:137)
ERROR: An Exception was thrown by Java... Please check the logs or the console.
thread 'main' panicked at src/main.rs:61:11:
called `Result::unwrap()` on an `Err` value: JavaError("org.astonbitecode.j4rs.errors.InvocationException: Error while accessing field position of Class java.lang.Object\n\tat org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.field(JsonInvocationImpl.java:141)\nCaused by: java.lang.NoSuchFieldException: position\n\tat java.base/java.lang.Class.getField(Class.java:2343)\n\tat org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.getField(JsonInvocationImpl.java:167)\n\tat org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.field(JsonInvocationImpl.java:137)\n")
```

**Comment by astonbitecode** [comment]
First, let me note two things:

1. There is no need to add the `itextpdf-5.5.13.4.jar` twice. Once it is added in a `Jvm`, all the Jvms created later will also have its classes available. 
2. You may add the dependency using maven:

```rust
jvm.deploy_artifact(&MavenArtifact::from("com.itextpdf:itextpdf:5.5.13.4"))?;
```

Now, to the point: 

The error you see is actually because of Java's generics and type erasure (you may see a description and examples [here](https://www.baeldung.com/java-type-erasure) if you want).

Once you get the element from the Java `ArrayList`, the element's type is `Object`. If you cast it to the type you __know__ it is, everything will work:

```rust
   fn bad() -> Result<(), errors::J4RsError> {
        let jvm = JvmBuilder::new().build()?;
    
        let pos = create_pos0(&jvm)?;
    
        let list = jvm.create_instance("java.util.ArrayList", InvocationArg::empty())?;
        jvm.invoke(&list, "add", &[InvocationArg::from(pos)])?;
    
        let pos0 = jvm.invoke(
            &list,
            "get",
            &[InvocationArg::try_from(0i32)?.into_primitive()?],
        )?;

        // Do the casting
        let pos0_casted = jvm.cast(&pos0, "com.itextpdf.text.pdf.AcroFields$FieldPosition")?;
    
        try_get_field_from_pos(&jvm, pos0_casted)?;
    
        Ok(())
    }
```

**Comment by showier-drastic** [comment]
Understood, thanks!!!

It would be better if this behaviour is documented somewhere, as it's somewhat un-intuitive for Java beginners (which I believe some users of this library are).

**Comment by showier-drastic** [comment]
One small comment regarding `deploy_artifact`: Should I call it at runtime or in `build.rs`?

**Comment by showier-drastic** [comment]
Thanks again!!
