### ISSUE TITLE
Do not throw error when dynamic under deps not found

### ISSUE THREAD

**Issue by wangxiaoying** [astonbitecode/j4rs#35]
Currently, the project will print following message and error when dynamic libs under deps is not found:

```
The Callbacks are not initialized because the j4rs lib was not found. You may ignore this error if you don't use callbacks.
java.lang.UnsatisfiedLinkError: no j4rs in java.library.path: [/usr/local/lib/python3.8/dist-packages/connectorx/dependencies/deps, /usr/lib, /lib]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2673)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at org.astonbitecode.j4rs.api.invocation.NativeCallbackToRustChannelSupport.initialize(NativeCallbackToRustChannelSupport.java:33)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeMethod(JsonInvocationImpl.java:179)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeStatic(JsonInvocationImpl.java:80)
```

Is it possible to disable the checking for the dynamic libraries for projects that do not use callback? It will be much more convenient for development.

**Comment by astonbitecode** [comment]
You may call the `skip_setting_native_lib` during the Jvm creation:

```rust
let jvm: Jvm = JvmBuilder::new().skip_setting_native_lib().build().unwrap();
```

This should be enough for what you need.
