### ISSUE TITLE
build.rs issue: $CARGO_HOME/env does not exist

### ISSUE THREAD

**Issue by blueridanus** [astonbitecode/j4rs#4]
The crate fails to build, panicking at [build.rs:176](https://github.com/astonbitecode/j4rs/blob/master/rust/build.rs#L176):

```rust
// env_file_path = $CARGO_HOME/env 
let mut f = File::open(&env_file_path)?; 
```

<details>
<summary>
backtrace
</summary>

```rust
--- stderr
thread 'main' panicked at 'Initialize Environment: J4rsBuildError { description: "Os { code: 2, kind: NotFound,message: \"No such file or directory\" }" }', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at libcore/macros.rs:26
   9: <core::result::Result<T, E>>::expect
             at libcore/result.rs:835
  10: build_script_build::main
             at ./build.rs:54
  11: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start
```
</details>

---
`ls -f` in my `$CARGO_HOME` returns:
```
bin  .crates.toml  ..  .  registry
```
There is no `env` entry.

**Comment by blueridanus** [comment]
Additionally, `touch env` on `$CARGO_HOME` seems to have fixed the issue.

**Comment by astonbitecode** [comment]
Hi, thanks for the report.

Will need to add the check whether the file exists or not...

However, after you created the file I would expect to work with no issues. Can you try to execute 
```source $CARGO_HOME/env``` and see if the LD_LIBRARY_PATH is correctly set for the session?

Generally the issue is that the `$LD_LIBRARY_PATH` should include the path that contains the `libjvm.so`.
This is needed for the creation of the JVM. The `build.rs` tries to set up some things automatically but apparently there are some glitches that need fix.
