### ISSUE TITLE
Method 'foobar' was not found when calling instance from Rust

### ISSUE THREAD

**Issue by s1ck** [astonbitecode/j4rs#42]
Hey. I'm playing around with your crate and I want to try some examples for calling Rust code from Java.

I'm stuck at using a callback to let rust call a method on a Java object.

Basically I have

```java
public class Main {
    @FunctionalInterface
    public static interface Callback {
        void call(long value);
    }
    
    private static native void dotproductcallback(Instance<long[]> vectorA, Instance<long[]> vectorB, Instance<Callback> callback);
    
    static {
        System.loadLibrary("mylib");
    }
    
    public static void main(String[] args) {
        var callback = new Callback() {
            public void call(long result) {
                System.out.println("dot product = " + result);
            }
        };
        Main.dotproductcallback(
            Java2RustUtils.createInstance(vectorA),
            Java2RustUtils.createInstance(vectorB),
            Java2RustUtils.createInstance(callback)
        );
    }
}
```

and 

```rust
#[call_from_java("j4rs.Main.dotproductcallback")]
fn dot_product_callback(vector_a: Instance, vector_b: Instance, callback: Instance) {
    // Attach current thread to an active JVM
    let jvm = Jvm::attach_thread().unwrap();
    // Get the vectors from the instances
    // Note, that those are owned vecs, changing them has no effect on the original data.
    let vector_a: Vec<i64> = jvm.to_rust(vector_a).unwrap();
    let vector_b: Vec<i64> = jvm.to_rust(vector_b).unwrap();

    // Compute the dot product
    let dot_product = dot_product(&vector_a, &vector_b);
    let ia = InvocationArg::try_from(dot_product).unwrap();

    // Invoke callback method
    let _ = jvm.invoke(&callback, "call", &[ia]).unwrap();
}
```

When I execute this it doesn't seem to be able to find the `call` method:

```
Method call was not found in j4rs.Main$1 or its ancestors.
```

I tried creating a class `Callback` and also tried the channel example. Both lead to the same result of the method `call` not being found on the instance. I also tried using `Callback` as a class and instantiating it in Rust and not passing it down. Same result, couldn't find the method. Any suggestions?

**Comment by s1ck** [comment]
Ok, one problem is the argument type of `call`, it should be `Instance<Long>`. And it seems that anonymous classes won't work.. if I instead do:

```java
public class Callback {
    public void call(Instance<Long> result) {
        System.out.println("dot product = " + Java2RustUtils.getObjectCasted(result));
    }
}
```

and

```rust
    // Invoke method
    let _ = jvm.invoke(&callback, "call", &vec![ia]).unwrap();
```

I am getting

```
Exception in thread "main" org.astonbitecode.j4rs.errors.InvocationException: While invoking method call of Class j4rs.Callback
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invoke(JsonInvocationImpl.java:73)
        at j4rs.Main.dotproductcallback(Native Method)
        at j4rs.Main.main(Main.java:53)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeMethod(JsonInvocationImpl.java:184)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invoke(JsonInvocationImpl.java:70)
        ... 2 more
```

:thinking:

**Comment by astonbitecode** [comment]
Hi,

you were actually finding the solution while I was typing the answer :)

`j4rs` was initially implemented to allow Rust applications to call Java (Rust -> Java direction). In this context, a callback is actually a callback from Java to Rust.

The "callback" you try to achieve is actually a simple Rust -> Java invocation.

As you found out by yourself, in your last example, the argument should actually be a pure `Long`:

```java
public class Callback {
    public void call(Long result) {
        System.out.println("dot product = " + result);
    }
}
```

Using `Long` instead of `long` you don't need the `into_primitive` call:

```rust
    let dot_product: i64 = dot_product(&vector_a, &vector_b);
    let ia = InvocationArg::try_from(dot_product).unwrap();

    // Invoke method
    let _ = jvm.invoke(&callback, "call", &vec![ia]).unwrap();
```

**Comment by s1ck** [comment]
Thanks! Great. It also works if I define a `interface Callback` in a separate file (non-nested) and pass implementations to the native method. For some reason it does not work if the `Callback` interface is nested directly in `Main` and I pass an anonymous instance.

**Comment by s1ck** [comment]
Thanks for the reply :) While I appreciate the docs on `j4rs`, it might be useful to add such a callback example to the `j4rs-java-call-rust` docs.
