### ISSUE TITLE
Unable to run j4rs，Error occurred during initialization of VM

### ISSUE THREAD

**Issue by fangheng** [astonbitecode/j4rs#49]
Hello, I reported an error while running j4rs，
I need the help of a technical guru, thank you very much, here is the error message and my environment version information

```
`Error occurred during initialization of VM
java.lang.Error: java.lang.ClassNotFoundException: org.astonbitecode.j4rs.api.deploy.J4rsClassLoader
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1469)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1436)
Caused by: java.lang.ClassNotFoundException: org.astonbitecode.j4rs.api.deploy.J4rsClassLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.lang.SystemClassLoaderAction.run(ClassLoader.java:2209)
	at java.lang.SystemClassLoaderAction.run(ClassLoader.java:2195)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1456)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1436)

error: process didn't exit successfully: `target\debug\demo.exe` (exit code: 1)`
```

Action: Using cargo clean or cargo build will not work。

**environment:**

**j4rs** ：
```
branch：master
tags：v0.15.2
```
**cargo Version**: 
`cargo 1.65.0 (4bc8f24d3 2022-10-20),`

**java Version**:  

```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Operating system**: 
 `windows 10`

It's really urgent. Thank you again！！！

**Comment by astonbitecode** [comment]
Hi, this is because you use an older Java version. Please try to initialize your Jvm, using the `with_default_classloader()`. Eg:

```rust
let jvm = JvmBuilder::new().with_default_classloader().build()?;
```

**Comment by fangheng** [comment]
> Hi, this is because you use an older Java version. Please try to initialize your Jvm, using the `with_default_classloader()`. Eg:
> 
> ```rust
> let jvm = JvmBuilder::new().with_default_classloader().build()?;
> ```


Thank you for your timely reply. I have tried using your scheme, and the previous mistake is indeed gone.
But now another error has been reported, as shown below：
> 
> 


```
java.lang.NoClassDefFoundError: org/astonbitecode/j4rs/api/instantiation/NativeInstantiationImpl
Caused by: java.lang.ClassNotFoundException: org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
thread 'main' panicked at 'TODO: panic message: JavaError("An Exception was thrown by Java while creating global ref... Please check the logs or the console.")',
```

**Comment by astonbitecode** [comment]
Using the default classloader as you did, is compatible with older Java versions.

Please do the following to check the results:

1. Run your application having set the env var `J4RS_CONSOLE_LOG_LEVEL=debug`:

```
set J4RS_CONSOLE_LOG_LEVEL=debug
cargo run
```

2. Run your application by actually invoking the executable without using cargo. If your executable is called __myexec.exe__ run it directly instead.

**Comment by astonbitecode** [comment]
It seems the issue is canonicalizing UNC paths on Windows. [Here](https://github.com/rust-lang/rust/issues/42869) are more details.

I am pushing a fix shortly for it.

Thanks for reporting.

**Comment by rollbor** [comment]
> It seems the issue is canonicalizing UNC paths on Windows. [Here](https://github.com/rust-lang/rust/issues/42869) are more details.
> 
> I am pushing a fix shortly for it.
> 
> Thanks for reporting.



> It seems the issue is canonicalizing UNC paths on Windows. [Here](https://github.com/rust-lang/rust/issues/42869) are more details.
> 
> I am pushing a fix shortly for it.
> 
> Thanks for reporting.



The problem has been solved, thank you, but it seems that UNC does not support the existence of Chinese path in the project, I wonder whether it will be compatible later. But I try to expose my problems as much as possible to avoid repeating them!
