### ISSUE TITLE
Trouble calling a variadic constructor

### ISSUE THREAD

**Issue by fredmorcos** [astonbitecode/j4rs#5]
Are variadic methods supported? If not, what could be a temporary workaround?

I am trying to call [this constructor from JavaParser](https://static.javadoc.io/com.github.javaparser/javaparser-symbol-solver-core/3.13.6/com/github/javaparser/symbolsolver/resolution/typesolvers/CombinedTypeSolver.html#CombinedTypeSolver-com.github.javaparser.symbolsolver.model.resolution.TypeSolver...-) using the following:

```rust
const COMBINED_TYPE_SOLVER: &str =
    "com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver";
const REFLECTION_TYPE_SOLVER: &str =
    "com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver";

fn main() -> Result<(), Box<dyn Error>> {
    let jvm = JvmBuilder::new().classpath_entries(classpaths()).build()?;
    let reflection_ts = jvm.create_instance(REFLECTION_TYPE_SOLVER, &[])?;
    let combined_ts =
        jvm.create_instance(COMBINED_TYPE_SOLVER, &[InvocationArg::from(reflection_ts)])?;
    Ok(())
}
```

and I get the following exception:

```
Exception in thread "main" org.astonbitecode.j4rs.errors.InstantiationException: Cannot create instance of com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver
	at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.instantiate(NativeInstantiationImpl.java:36)
Caused by: java.lang.NoSuchMethodException: com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver.<init>(com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver)
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.createInstance(NativeInstantiationImpl.java:59)
	at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.instantiate(NativeInstantiationImpl.java:33)
Error: JavaError("An Exception was thrown by Java while creating global ref... Please check the logs or the console.")
```

**Comment by astonbitecode** [comment]
They were planned to be supported in a future release, but since you need them, I pushed an implementation to the master. You may use it like following:

```rust
let jvm: Jvm = super::new_jvm(Vec::new(), Vec::new()).unwrap();

// Create the args of the constructor
let s1 = InvocationArg::from("abc");
let s2 = InvocationArg::from("def");
let s3 = InvocationArg::from("ghi");

// Create a Java Array with the above args
let arr_instance = jvm.create_java_array("java.lang.String", &vec![s1, s2, s3]).unwrap();

// Supposing that the MyTest class has a constructor
// public MyTest(String... args) {...}
// Pass the arr_instance
let test_instance = jvm.create_instance("org.astonbitecode.j4rs.tests.MyTest", &[InvocationArg::from(arr_instance)]).unwrap();
```

**Comment by fredmorcos** [comment]
Wow.. awesome! Thanks!

**Comment by fredmorcos** [comment]
Two problems popped up (using master):

- I cannot create an array of elements of an interface. Here TypeSolver is an interface, and ReflectionTypeSolver implements that interface. I am not very well versed in Java, but shouldn't I be able to create an array like `Interface arr[] = {InterfaceImplementer1, InterfaceImplementer2, ...};`?

Here is what I am trying to do:

```rust
const TYPE_SOLVER: &str = "com.github.javaparser.symbolsolver.model.resolution.TypeSolver";
const REFLECTION_TYPE_SOLVER: &str =
    "com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver";

fn main() -> Result<(), Box<dyn Error>> {
    let jvm = JvmBuilder::new().classpath_entries(classpaths()).build()?;
    let reflection_ts = jvm.create_instance(REFLECTION_TYPE_SOLVER, &[])?;
    let combined_ts_args = jvm.create_java_array(
        TYPE_SOLVER,
        &[InvocationArg::from(reflection_ts)],
    )?;
    Ok(())
}
```

and here is the console output:

```
INFO: Setting library path to -Djava.library.path=/home/fred/Workspace/tmp/jat/target/debug/deps:/usr/lib:/lib
INFO: Passing to the Java world the name of the library to load: j4rs-7a223956fd3188e7
INFO: No JVMs exist. Creating a new one...
Exception in thread "main" org.astonbitecode.j4rs.errors.InstantiationException: Cannot create instance of com.github.javaparser.symbolsolver.model.resolution.TypeSolver
	at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.createJavaArray(NativeInstantiationImpl.java:54)
Caused by: java.lang.IllegalArgumentException: Could not create Java array. All the arguments should be of class com.github.javaparser.symbolsolver.model.resolution.TypeSolver
	at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.doCreateJavaArray(NativeInstantiationImpl.java:81)
	at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.createJavaArray(NativeInstantiationImpl.java:51)
Error: JavaError("An Exception was thrown by Java while creating global ref... Please check the logs or the console.")
```

- The second issue is that `create_instance` does not work even with an array of ReflectionTypeSolvers, here is the example:

```rust
const COMBINED_TYPE_SOLVER: &str =
    "com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver";
const REFLECTION_TYPE_SOLVER: &str =
    "com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver";

fn main() -> Result<(), Box<dyn Error>> {
    let jvm = JvmBuilder::new().classpath_entries(classpaths()).build()?;
    let reflection_ts = jvm.create_instance(REFLECTION_TYPE_SOLVER, &[])?;
    let combined_ts_args = jvm.create_java_array(
        REFLECTION_TYPE_SOLVER,
        &[InvocationArg::from(reflection_ts)],
    )?;
    let combined_ts = jvm.create_instance(
        COMBINED_TYPE_SOLVER,
        &[InvocationArg::from(combined_ts_args)],
    )?;
    Ok(())
}
```

and the console output:

```
INFO: Setting library path to -Djava.library.path=/home/fred/Workspace/tmp/jat/target/debug/deps:/usr/lib:/lib
INFO: Passing to the Java world the name of the library to load: j4rs-7a223956fd3188e7
INFO: No JVMs exist. Creating a new one...
Exception in thread "main" org.astonbitecode.j4rs.errors.InstantiationException: Cannot create instance of com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver
	at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.instantiate(NativeInstantiationImpl.java:36)
Caused by: java.lang.NoSuchMethodException: com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver.<init>([Lcom.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;)
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.createInstance(NativeInstantiationImpl.java:68)
	at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.instantiate(NativeInstantiationImpl.java:33)
Error: JavaError("An Exception was thrown by Java while creating global ref... Please check the logs or the console.")
```

I think something might be wrong with `java.lang.NoSuchMethodException: com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver.<init>([Lcom.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;)`

**Comment by astonbitecode** [comment]
Try to cast the ReflectionTypeSolver to TypeResolver:

let reflection_ts = jvm.create_instance(REFLECTION_TYPE_SOLVER, &[])?;

let ts = jvm.cast(&reflection_ts, TYPE_RESOLVER)?;

And then create the array:

let combined_ts_args = jvm.create_java_array( TYPE_SOLVER, &[InvocationArg::from(ts)], )?; 

I will losen the strict type checking when creating the arrays so that you don't need casting.

**Comment by astonbitecode** [comment]
I guess we can close this one. 

@fredmorcos feel free to comment if you still have issues with the variadic constructors.

**Comment by fredmorcos** [comment]
Hello @astonbitecode, sorry for not responding earlier, that's quite disrespectful of me. Calling variadic constructors is working as expected. Thank you very much!
