### ISSUE TITLE
Method was not found in class

### ISSUE THREAD

**Issue by ziyak97** [astonbitecode/j4rs#52]
Hey so I create my instance from a jar file as shown below
  
```
let jvm = JvmBuilder::new()
    .classpath_entry(ClasspathEntry::new(
        "/Users/ziyak/Desktop/exps/rust-exp/src/bundletool-all-1.14.0.jar",
    ))
    .build()
    .expect("Failed to create JVM");
```

and then attempt to call the main method in the com.android.tools.build.bundletool.BundleToolMain class of the jar file as shown below
        
```
match jvm.invoke_static(
    "com.android.tools.build.bundletool.BundleToolMain",
    "main",
    &java_args,
) {
    Ok(_) => println!("Success"),
    Err(e) => println!("Error: {:?}", e),
}
```

this however gives me a java.lang.NoSuchMethodException error

this is the error stack

```
Exception in thread "main" org.astonbitecode.j4rs.errors.InvocationException: Error while invoking method main of Class com.android.tools.build.bundletool.BundleToolMain
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeStatic(JsonInvocationImpl.java:83)
Caused by: java.lang.NoSuchMethodException: Method main was not found in com.android.tools.build.bundletool.BundleToolMain or its ancestors.
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.findMethodInHierarchy(JsonInvocationImpl.java:242)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.findMethodInHierarchy(JsonInvocationImpl.java:244)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeMethod(JsonInvocationImpl.java:174)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeStatic(JsonInvocationImpl.java:80)
Error: JavaError("An Exception was thrown by Java... Please check the logs or the console.")
```

the actual code can be found here - https://github.com/google/bundletool/blob/master/src/main/java/com/android/tools/build/bundletool/BundleToolMain.java

It is able to find the class but not invoke the method.

I am not sure if I am doing something wrong plz let me know.

**Comment by ziyak97** [comment]
My method had the args individually sent as separate args instead of the java array I expected it to be.

This is what fixed it - 

```
  let arr_instance = jvm.create_java_array("java.lang.String", &java_args).unwrap();

  match jvm.invoke_static(
      "com.android.tools.build.bundletool.BundleToolMain",
      "main",
      vec![InvocationArg::try_from(arr_instance).unwrap()].as_ref(),
  ) {
      Ok(_) => println!("Success"),
      Err(e) => println!("Error: {:?}", e),
  }
```
