### ISSUE TITLE
How to params an instance ref?

### ISSUE THREAD

**Issue by niuhuan** [astonbitecode/j4rs#58]
I want got a spring bean use j4rs, but got method not found , I tried class and String param.

And sometimes instance needs to be used repeatedly as a parameter.

```rust
    let context = { an java return spring context object  } ; 
    let runner_class = jvm.static_class("rijq.framework.handlers.InitRunner")?;
    let runner = jvm.invoke(
        &context,
        "getBean",
        vec![InvocationArg::try_from(runner_class).unwrap()].as_ref(),
    )?;
```

```
Exception in thread "main" org.astonbitecode.j4rs.errors.InvocationException: While invoking method getBean of Class org.springframework.context.ConfigurableApplicationContext
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invoke(JsonInvocationImpl.java:73)
Caused by: java.lang.NoSuchMethodException: Method getBean was not found in org.springframework.context.ConfigurableApplicationContext or its ancestors.
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.findMethodInHierarchy(JsonInvocationImpl.java:242)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeMethod(JsonInvocationImpl.java:174)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invoke(JsonInvocationImpl.java:70)
```

```
DEBUG: Dropping an instance of java.lang.String
DEBUG: Retrieving static class rijq.framework.handlers.InitRunner
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invoke(JsonInvocationImpl.java:73)
Caused by: java.lang.NoSuchMethodException: Method getBean was not found in org.springframework.context.ConfigurableApplicationContext or its ancestors.
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.findMethodInHierarchy(JsonInvocationImpl.java:242)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeMethod(JsonInvocationImpl.java:174)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invoke(JsonInvocationImpl.java:70)
DEBUG: Dropping an instance of known_in_java_world
```

**Comment by astonbitecode** [comment]
How do you instantiate the Spring application? Is it Spring Boot? The Spring-Boot generated jars have a spring-specific structure and cannot be used as a normal Jar.

If you need to have both Spring Boot jar and a traditional one, you should try something like:

https://codingnconcepts.com/spring-boot/spring-boot-project-as-dependency/

**Comment by niuhuan** [comment]
Yes, I saw the article you told others before and it was very user-friendly. I successfully launched Spring.

**Comment by astonbitecode** [comment]
Ok.

`Jvm#static_class` does not actually return a `Class`. It is actually a handle that allows acting on a class instead of an instance.

For example, doing a `java.lang.System.out.println("Hello World")`,  implies getting the static field `out` of the `System` class and invoke this, with the `"Hello World"` String.

```rust
let system = jvm.static_class("java.lang.System")?;
let _ = jvm.into_chain(system)
      .field("out")?
      .invoke("println", &[InvocationArg::try_from("Hello World")?])?
      .collect();
```

That being said, you might achieve what you want by creating a `Class` and use it to invoke the `getBean` with something like the following:

```rust
// Java code: var runner_class = Class.forName("rijq.framework.handlers.InitRunner")
let runner_class = jvm.invoke_static("java.lang.Class", "forName", &[InvocationArg::try_from("rijq.framework.handlers.InitRunner")?])?;
// Java code: context.getBean(runner_class)
let bean_instance = jvm.invoke(&context, "getBean", &[InvocationArg::try_from(runner_class)?])?;
```
