### ISSUE TITLE
ClassNotFound on Android 

### ISSUE THREAD

**Issue by XizhiXu** [astonbitecode/j4rs#59]
On Java side, if we want to get an object from a serialized `Instance`, we will call `Java2RustUtils.getObjectCasted()`.
Then we're going to look up the class with the given name in the system class loader, as util function says here:
https://github.com/astonbitecode/j4rs/blob/52dd1732cf5e3a4aa1ae8a0177cc316dc8316a99/java/src/main/java/org/astonbitecode/j4rs/utils/Utils.java#L22-L45

We can do this in the general Java world.
While on the Android system, the system class loader usually doesn't contain any classes under the application package. (depending on implementation https://developer.android.com/reference/java/lang/ClassLoader#getSystemClassLoader())

Tried on different devices, it turned out that the custom object conversion will raise **ClassNotFoundException**.

**Comment by astonbitecode** [comment]
Hi,

can you elaborate? As I understand, you try to call a Rust library from a Java Android app. I have created an [example](https://github.com/astonbitecode/j4rs-android-test), where you may find a Rust library being built and set up in order to be used by Android. The Android App calls this library in several ways (as you may find out in the `MainActivity.java`) and one of the calls includes a custom object that gets serialized and used by both Rust and Java world. 

This example works without issues from what I see. Can you change it in a way that you saw the `ClassNotFoundException` in order to get a more detailed picture of your expectation?

**Comment by XizhiXu** [comment]
Thanks for your response.

Yep, I was trying to call Rust from Java. The problem is when I'm going to get the object from the `Instance` in Java, the exception is thrown due to the reason I mentioned above.

In your example, the runtime error stack is:
```
Process: com.example.j4rstest, PID: 4836
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.j4rstest/com.example.j4rstest.MainActivity}: org.astonbitecode.j4rs.errors.JsonCodecException: While creating JsonValueCallbackImpl: Could not decode {"number":3333}
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3374)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7682)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: org.astonbitecode.j4rs.errors.JsonCodecException: While creating JsonValueCallbackImpl: Could not decode {"number":3333}
 at org.astonbitecode.j4rs.api.value.JsonValueImpl.<init>(JsonValueImpl.java:50)
 at org.astonbitecode.j4rs.api.value.JsonValueFactory.create(JsonValueFactory.java:25)
 at org.astonbitecode.j4rs.api.Instance.getOrDeserializeJavaObject(Instance.java:116)
 at org.astonbitecode.j4rs.api.java2rust.Java2RustUtils.getObjectCasted(Java2RustUtils.java:28)
 at com.example.j4rstest.RustFunctionCalls.doCallWithCustomObject(RustFunctionCalls.java:39)
 at com.example.j4rstest.MainActivity.onCreate(MainActivity.java:28)
 at android.app.Activity.performCreate(Activity.java:7815)
 at android.app.Activity.performCreate(Activity.java:7804)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513) 
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109) 
 at android.os.Handler.dispatchMessage(Handler.java:107) 
 at android.os.Looper.loop(Looper.java:214) 
 at android.app.ActivityThread.main(ActivityThread.java:7682) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
Caused by: java.lang.ClassNotFoundException: com.example.j4rstest.api.dto.TestDto
 at java.lang.Class.classForName(Native Method)
 at java.lang.Class.forName(Class.java:454)
 at org.astonbitecode.j4rs.utils.Utils.forNameEnhanced(Utils.java:43)
 at org.astonbitecode.j4rs.json.Codec.decode(Codec.java:38)
 at org.astonbitecode.j4rs.api.value.JsonValueImpl.<init>(JsonValueImpl.java:47)
 at org.astonbitecode.j4rs.api.value.JsonValueFactory.create(JsonValueFactory.java:25) 
 at org.astonbitecode.j4rs.api.Instance.getOrDeserializeJavaObject(Instance.java:116) 
 at org.astonbitecode.j4rs.api.java2rust.Java2RustUtils.getObjectCasted(Java2RustUtils.java:28) 
 at com.example.j4rstest.RustFunctionCalls.doCallWithCustomObject(RustFunctionCalls.java:39) 
 at com.example.j4rstest.MainActivity.onCreate(MainActivity.java:28) 
 at android.app.Activity.performCreate(Activity.java:7815) 
 at android.app.Activity.performCreate(Activity.java:7804) 
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318) 
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349) 
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513) 
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109) 
 at android.os.Handler.dispatchMessage(Handler.java:107) 
 at android.os.Looper.loop(Looper.java:214) 
 at android.app.ActivityThread.main(ActivityThread.java:7682) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.j4rstest.api.dto.TestDto" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib64, /system/product/lib64, /system/lib64, /system/product/lib64]]
 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
```

**Comment by trik** [comment]
@XizhiXu i'm facing the same problem, trying to instantiate my own classes on Android. As a workaround, i changed the getSystemClassLoader call with

```java
java.lang.Thread.currentThread().getContextClassLoader();
```

**Comment by astonbitecode** [comment]
Hi, thanks for the update. 

I will find some time to deal with it.

**Comment by trik** [comment]
@astonbitecode great work! it works like a charm and your solution works also in multi threaded context.
the mine still had ClassNotFoundExceptions on spawn threads

**Comment by astonbitecode** [comment]
Thanks for checking it @trik ! 

I will create a patch release to include this in (v0.16.1).
