### ISSUE TITLE
When C1 implements IF2 that extends IF1, the default method contained in IF1 cannot be found.(NoSuchMethodException)

### ISSUE THREAD

**Issue by Leart-Loen** [astonbitecode/j4rs#71]
`/path/to/tmp.jar `
``` java
// ---- `IF1.java` ----
package xx.yyy;

public interface IF1 {
    default public void if1_f1(){
        System.out.println("gap, default, no impl");
    };
}
```
``` java
// ---- `IF2.java` ----
package xx.yy;

public interface IF2 extends IF1 {
    default public void if2_f1() {
        System.out.println("no gap, default, impl");
    }

    public void if2_f2();

    default public void if2_f3() {
        System.out.println("no gap, default, no impl");
    }
}
```
``` java
// ---- `C1.java` ----
package xx.yyy;

public final class C1 implements IF2 {
    @Override
    public void if2_f2() {
        System.out.println("no default");
    }
}
```
-------------------RUST_SIDE------------------
``` rust
use j4rs::{ClasspathEntry, Jvm, JvmBuilder};

fn main() {
    let entry = ClasspathEntry::new("/path/to/tmp.jar");
    let jvm: Jvm = JvmBuilder::new().classpath_entry(entry).build().unwrap();
    let instance = jvm.create_instance("xx.yyy.C1", &[]).unwrap();

    let _ = jvm.invoke(&instance, "if2_f1", &[]).unwrap();
    let _ = jvm.invoke(&instance, "if2_f2", &[]).unwrap();

    let _ = jvm.invoke(&instance, "if2_f3", &[]).unwrap();

    let _ = jvm.invoke(&instance, "if1_f1", &[]).unwrap(); // <--------------panicked here.
}
```
```
no gap, default, impl
no default
no gap, default, no impl
Exception in thread "main" org.astonbitecode.j4rs.errors.InvocationException: While invoking method if1_f1 of Class xx.yyy.C1
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invoke(JsonInvocationImpl.java:75)
Caused by: java.lang.NoSuchMethodException: Method if1_f1 was not found in xx.yyy.C1 or its ancestors.
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.findMethodInHierarchy(JsonInvocationImpl.java:304)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.findMethodInHierarchy(JsonInvocationImpl.java:306)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeMethod(JsonInvocationImpl.java:186)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invoke(JsonInvocationImpl.java:72)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JavaError("An Exception was thrown by Java... Please check the logs or the console.")', src/main.rs:13:50
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/result.rs:1076:23
   4: find_bug_rs::main
             at ./src/main.rs:13:13
   5: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I am temporarily using `cast` to avoid this issue, but is this a designed behavior with reasons, or is it a bug?

Moreover, sometimes a function overloads these two interfaces separately. In this case, when passing an instance of a class which implements these two interfaces to the function, j4rs always tends to call one of them, even if `cast` is used.

**Comment by astonbitecode** [comment]
Hi! 

Thanks for the report.
This was a bug and hopefully it is now fixed in the master. 
Could you please verify yourself?

**Comment by Leart-Loen** [comment]
yes, it works. thx a lot for your help!

**Comment by Leart-Loen** [comment]
o, i found that if there are more interfaces between the class C1 and the interface IF1, the issue seems still occurs.
i think i should reopen this issue. could you please continue working on this issue?

**Comment by Leart-Loen** [comment]
```
Class A
      |
      |
      implements IF1, IF2 ------------------
                  |                        |
                  |                        |
                  extends IF3              extents IF4
                          |                       |
                          |                       |
                          extends IF5             |
                                  |---------------|
                                  |
                                  extends IF6
```
like this. Class A cant invoke the method in IF6.

**Comment by Leart-Loen** [comment]
The current issue seems to no longer be a direct follow-up of this problem. It has occurred in my project but not in another one with a similar structure. If I can successfully reproduce the issue, I will open a new one with a fresh description. I'm sorry for the inconvenience I may have caused you.

**Comment by astonbitecode** [comment]
No worries.

If you see this happening again, please feel free to reopen.
I was thinking that the fix could have issues because of the shared resources (`LinkedHashSet`) between `Stream`s in recursion.
Theoretically this should not be a problem since the streams used are serial, but... who knows what the internals of Java holds for us.
