### ISSUE TITLE
The int type args is not match seemingly

### ISSUE THREAD

**Issue by LgnMs** [astonbitecode/j4rs#86]
```rust
// meta_data is ResultSetMetaData
// getColumnName is java.sql.*, the doc:
// String | getColumnName(int column)

let i: i32 = 1;
let column_name: String = conn.jvm.to_rust(conn.jvm.invoke(
      &meta_data,
      "getColumnName",
      &[InvocationArg::try_from(i)?],
  )?)?;

```
```
INFO: Setting classpath to -Djava.class.path=/Users/liguang/Desktop/workSpace/rust/data_process_center/target/debug/jassets/j4rs-0.17.2-jar-with-dependencies.jar:libs/kingbase8-8.6.0.jar
INFO: Setting library path to -Djava.library.path=/Users/liguang/Desktop/workSpace/rust/data_process_center/target/debug/deps:/usr/lib:/lib
INFO: Passing to the Java world the name of the library to load: j4rs-e8adfbc691899519
DEBUG: Creating a Jvm
INFO: No JVMs exist. Creating a new one...
DEBUG: Called set_jni_get_method_id
DEBUG: Called set_jni_get_static_method_id
DEBUG: Called set_jni_new_object
DEBUG: Called set_jni_new_string_utf
DEBUG: Called set_jni_get_string_utf_chars
DEBUG: Called set_jni_release_string_utf_chars
DEBUG: Called set_jni_call_object_method
DEBUG: Called set_jni_call_byte_method
DEBUG: Called set_jni_call_short_method
DEBUG: Called set_jni_call_int_method
DEBUG: Called set_jni_call_long_method
DEBUG: Called set_jni_call_float_method
DEBUG: Called set_jni_call_double_method
DEBUG: Called set_jni_call_void_method
DEBUG: Called set_jni_call_static_object_method
DEBUG: Called set_jni_new_object_array
DEBUG: Called set_jni_set_object_array_element
DEBUG: Called set_jni_exception_check
DEBUG: Called set_jni_exception_describe
DEBUG: Called set_jni_exception_clear
DEBUG: Called set_jni_delete_local_ref
DEBUG: Called set_jni_delete_global_ref
DEBUG: Called set_jni_new_global_ref
DEBUG: Called set_jni_throw_new
DEBUG: Called set_is_same_object
DEBUG: Called set_thread_local_env
DEBUG: Initializing NativeCallbackSupport with libname j4rs-e8adfbc691899519
DEBUG: Invoking static method initialize of class org.astonbitecode.j4rs.api.invocation.NativeCallbackToRustChannelSupport using 1 arguments
DEBUG: Called set_factory_class
DEBUG: Called set_factory_create_for_static_method
DEBUG: Called set_invocation_arg_class
DEBUG: Creating jobject from Rust basic for class java.lang.String
DEBUG: Calling the InvocationArg constructor with 'java.lang.String'
DEBUG: Called set_inv_arg_basic_rust_constructor_method
DEBUG: Called set_java_instance_class
DEBUG: Called set_invoke_static_method
DEBUG: Dropping an instance of known_in_java_world
DEBUG: Dropping an instance of java.lang.String
DEBUG: NativeCallbackSupport initialized
DEBUG: Invoking static method getConnection of class java.sql.DriverManager using 1 arguments
DEBUG: Creating jobject from Rust basic for class java.lang.String
DEBUG: Calling the InvocationArg constructor with 'java.lang.String'
DEBUG: Dropping an instance of java.lang.String
DEBUG: Invoking method createStatement of class known_in_java_world using 0 arguments
DEBUG: Called set_invoke_method
DEBUG: Invoking method executeQuery of class known_in_java_world using 1 arguments
DEBUG: Creating jobject from Rust basic for class java.lang.String
DEBUG: Calling the InvocationArg constructor with 'java.lang.String'
DEBUG: Dropping an instance of java.lang.String
DEBUG: Invoking method getMetaData of class known_in_java_world using 0 arguments
DEBUG: Invoking method getColumnCount of class known_in_java_world using 0 arguments
DEBUG: Called set_get_object_class_name_method
DEBUG: Called set_get_object_method
DEBUG: Called set_integer_class
DEBUG: Called set_integer_to_int_method
DEBUG: Dropping an instance of known_in_java_world
DEBUG: Invoking method next of class known_in_java_world using 0 arguments
DEBUG: Invoking the getJson method
DEBUG: Called set_get_json_method
DEBUG: Transforming jstring to rust String
DEBUG: Dropping an instance of known_in_java_world
DEBUG: Called set_integer_constructor_method
DEBUG: Invoking method getColumnName of class known_in_java_world using 1 arguments
DEBUG: Creating jobject from Rust basic for class java.lang.Integer
DEBUG: Calling the InvocationArg constructor with 'java.lang.Integer'
Exception in thread "main" org.astonbitecode.j4rs.errors.InvocationException: While invoking method getColumnName of Class java.sql.ResultSetMetaData
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invoke(JsonInvocationImpl.java:74)
Caused by: java.lang.NoSuchMethodException: Method getColumnName was not found in java.sql.ResultSetMetaData or its ancestors.
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.findMethodInHierarchy(JsonInvocationImpl.java:319)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeMethod(JsonInvocationImpl.java:188)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invoke(JsonInvocationImpl.java:70)
DEBUG: Dropping an instance of java.lang.Integer
DEBUG: Dropping an instance of known_in_java_world
DEBUG: Dropping an instance of known_in_java_world

```
what can i do?

**Comment by astonbitecode** [comment]
By default, `j4rs` uses boxed Java types when transforming types from Rust. 

Using [into_primitive](https://github.com/astonbitecode/j4rs?tab=readme-ov-file#java-primitives) you should be able to invoke the method you want.

**Comment by LgnMs** [comment]
> By default, `j4rs` uses boxed Java types when transforming types from Rust.
> 
> Using [into_primitive](https://github.com/astonbitecode/j4rs?tab=readme-ov-file#java-primitives) you should be able to invoke the method you want.

Thank you very much. It works. I didn't seriously read the docs.
