### ISSUE TITLE
use a java library?

### ISSUE THREAD

**Issue by jianshu93** [astonbitecode/j4rs#87]
Hello Team,

I have a java library to use, code will be like this: https://github.com/dynatrace-research/exaloglog-paper/blob/main/java/src/test/java/com/dynatrace/exaloglogpaper/DistinctCountUtilTest.java

How can I use it in j4rs?

Thanks,
Jianshu

**Comment by astonbitecode** [comment]
You should just create the `Jvm` specifying the class you want to include in the classpath. 

For example, if you have the Java class:

```java
package org.my;

public class Test {
    public void greet(String name) {
        System.out.println("Hello " + name);
    }
}
```

in a directory `/some/location/classes`, you can invoke the method `greet` like:

```rust
let jvm: Jvm = JvmBuilder::new().classpath_entry(ClasspathEntry::new("/some/location/classes")).build()?;
let test_instance = jvm.create_instance("org.my.Test", &[])?;
let name = InvocationArg::try_from("Chester")?;
let _ = jvm.invoke(&test_instance, "greet", &[name])?;
```

**Comment by astonbitecode** [comment]
It's been some time since this is inactive. Closing...

**Comment by davidjwriter** [comment]
I tried the above test and I am getting an `IllegalAccessException`?

Here is the Rust code: 

```
fn call_java() -> Result<(), J4RsError> {
    // Create a JVM
    let jvm = JvmBuilder::new()
        .classpath_entry(ClasspathEntry::new("/path/to/java/classes"))
        .build()?;

    let test_instance = jvm.create_instance("com.test.Test", InvocationArg::empty())?;
    let name = InvocationArg::try_from("Chester")?;
    let _ = jvm.invoke(&test_instance, "hello", &[name])?;

    Ok(())
}
```

This is the Java code:

```
package com.test;

class Test {

    public void hello(String someString) {
        System.out.println(someString);
    }
}
```

Here is the full stack trace:

```
Exception in thread "main" org.astonbitecode.j4rs.errors.InvocationException: While invoking method hello of Class com.test.Test
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invoke(JsonInvocationImpl.java:74)
Caused by: java.lang.IllegalAccessException: class org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl cannot access a member of class com.test.Test with modifiers "public"
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:394)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:714)
        at java.base/java.lang.reflect.Method.invoke(Method.java:571)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeMethod(JsonInvocationImpl.java:198)
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invoke(JsonInvocationImpl.java:70)
```
